### ISSUE TITLE
Parameters: [QuickStartS3URL, AvailabilityZones] do not exist in the template

### ISSUE THREAD

**Issue by jasmor** [aws-quickstart/quickstart-hashicorp-vault#7]
Hi,

The quickstart-hashicorp-vault-master.template is unable to run and rolls back with the following error:

> 	Parameters: [QuickStartS3URL, AvailabilityZones] do not exist in the template

**Comment by tonynv** [comment]
@jasmor  Thanks for reporting this issue.  
Please recursively clone the latest master. 
`git clone --recursive git@github.com:aws-quickstart/quickstart-hashicorp-vault.git` 
(to make sure you have the latest submodules)

Fixed in https://github.com/aws-quickstart/quickstart-hashicorp-vault/commit/a0cb789e20edc88dd3917375d89dfd09a4692cce

Please reopen if you still have issues after updating (recursively)

**Comment by jasmor** [comment]
@avattathil Excellent, works like a charm. Thanks for fixing this!
