### ISSUE TITLE
Deploy into new VPC fails at VaultServerLaunchConfiguration stage

### ISSUE THREAD

**Issue by henrychoi7** [aws-quickstart/quickstart-hashicorp-vault#86]
Hi there, I used this [template](https://github.com/aws-quickstart/quickstart-hashicorp-vault/blob/main/templates/quickstart-hashicorp-vault-master.template) to deploy into a new VPC but it keeps getting this error.

![image](https://user-images.githubusercontent.com/6342314/104675561-1a36b280-5729-11eb-85c6-25bac136196b.png)

I selected the parameter with `CIS-Ubuntu-1604-HVM` for Vault AMI. Any ideas on what is causing this error, or any troubleshooting steps I should attempt?

**Comment by gargana** [comment]
In order to use the CIS AMI one needs to subscribe to the AMI image in AWS marketplace: 
```
Note: The Center for Internet Security (CIS) AMI for Ubuntu Linux 16.04 LTS is
available as an optional, hardened AMI type. The image of Ubuntu Linux 16.04 LTS
is preconfigured by CIS according to their benchmark recommendations. For more
information, see CIS Ubuntu Linux 16.04 LTS Benchmark — Level 1.
```
[CIS Level 1 Ubuntu 16.04 LTS - Marketplace listing](https://aws.amazon.com/marketplace/pp/B078TPPXV2?qid=1588650469654)

Once you have that step done if you are still encountering this issue please reach out again.

Note: I am also busy updating the Quick Start to use the Ubuntu 20.04 LTS images currently: PR #91

**Comment by henrychoi7** [comment]
After that, I tried to deploy the Vault stack manually with the CIS Ubuntu 18.04, and it did work well. Thank you for your reply. I'll test out the Quick Start with the latest version and see if there are any errors. But for now, I'll close this issue.

Thanks again! :)
